apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatbot.fullname" . }}-config
  labels:
    {{- include "chatbot.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.env.PORT | quote }}
  DEBUG: {{ .Values.env.DEBUG | quote }}
